name: Build and Release new docker image
on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: read
  actions: read
  checks: write
  packages: write

jobs:
  build:
    name: Build, Test and Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Get image version from Dockerfile
      id: image-version
      run: |
        grep KEYCLOAK_DOCKER_REVISION Dockerfile | sed -e 's#.*=#version=#' >> $GITHUB_OUTPUT
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:${{ steps.image-version.outputs.version }}

